# Generated by Django 5.2.8 on 2025-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('index_number', models.CharField(max_length=20)),
                ('year_of_study', models.CharField(choices=[('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('selected_option', models.CharField(choices=[('Option 1', 'Option 1: Only 2 major modules'), ('Option 2', 'Option 2: 1 major module + 2 sub-modules'), ('Option 3', 'Option 3: 4 sub-modules only')], max_length=10)),
                ('category1_selections', models.JSONField(default=list)),
                ('category2_selections', models.JSONField(default=list)),
                ('category3_selections', models.JSONField(default=list)),
                ('category4_selections', models.JSONField(default=list)),
                ('category5_selections', models.JSONField(default=list)),
                ('category6_selections', models.JSONField(default=list)),
                ('category7_selections', models.JSONField(default=list)),
                ('software_selections', models.JSONField(default=list)),
                ('additional_courses', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
